import React from "react";
import { FaSearch } from "react-icons/fa";
const Rear = () => {
  return (
    <div className="w-1/3 h-fit flex flex-col justify-start py-5 px-10">
      <input type="text" className="hidden" />
      <div className="px-2 py-3 border-[1px] rounded-xl  text-[#A2A3BB] text-[10px] flex flex-row justify-between">
        Search <FaSearch className="self-center text-[12px]" />
      </div>

      <div className="bg-[#393B70] mt-4 h-fit py-2 rounded-2xl flex flex-col">
        <p className="px-6 py-1 text-[#fff] font-medium text-[14px]">
          Subscribe To Premium
        </p>
        <p className="text-[#A2A3BB] px-6 text-[12px]">
        Subscribe today to unlock a variety of premium features, gain access to exclusive tools designed to enhance your experience, and, if eligible, receive a fair share of ongoing revenue generated by your contributions. Take advantage.
        </p>
        <button className="bg-gradient-to-t from-[#bab153] to-[#ad8a1f] px-4 py-2 rounded-2xl active:scale-95 transition-all duration-150 text-[10px] mt-2  self-end  mr-6 mb-2 font-medium text-white">
          Get it
        </button>
      </div>
      <div className="bg-[#393B70] h-80 mt-4 rounded-2xl flex flex-col p-4">
  
  <div className="grid grid-cols-2 gap-4 text-white">
   
    <div className="p-4 rounded-2xl">
      <p className="text-2xl font-semibold">Basic</p>
      <p className="text-xl font-bold mt-2">₹215.87 / month</p>
      <ul className="mt-4 space-y-2 text-sm">
        <li>Organize with bookmark folders</li>
        <li>Access to Highlights tab</li>
        <li>Ability to edit posts</li>
        <li>Share longer videos</li>
      </ul>
    </div>
   
    <div className=" p-4 rounded-2xl">
      <p className="text-2xl font-semibold">Premium</p>
      <p className="text-xl font-bold mt-2">₹566.67 / month</p>
      <ul className="mt-4 space-y-2 text-sm">
        <li>Fewer ads in "For You"</li>
        <li>Bigger reply boost</li>
        <li>Verified checkmark</li>
        <li>Access to Grok 2 AI Assistant</li>
      </ul>
    </div>
  </div>
</div>

    </div>
  );
};

export default Rear;
